#include "app_ipcam_paramparse.h"
#define NAME2STR(NAME)              (#NAME)
#define MODEL_NAME(MODEL_NAME)      NAME2STR(MODEL_NAME)
//ai common attribute
const char *ai_supported_model[TDL_MODEL_MAX] = {
    [TDL_MODEL_YOLOV8N_DET_MONITOR_PERSON]   = MODEL_NAME(TDL_MODEL_YOLOV8N_DET_MONITOR_PERSON),
    [TDL_MODEL_SCRFD_DET_FACE]               = MODEL_NAME(TDL_MODEL_SCRFD_DET_FACE),
    [TDL_MODEL_KEYPOINT_YOLOV8POSE_PERSON17] = MODEL_NAME(TDL_MODEL_KEYPOINT_YOLOV8POSE_PERSON17),
    [TDL_MODEL_CLS_SOUND_BABAY_CRY]          = MODEL_NAME(TDL_MODEL_CLS_SOUND_BABAY_CRY),
    [TDL_MODEL_YOLOV8N_DET_PERSON_VEHICLE]   = MODEL_NAME(TDL_MODEL_YOLOV8N_DET_PERSON_VEHICLE),
    [TDL_MODEL_TRACKING_FEARTRACK]           = MODEL_NAME(TDL_MODEL_TRACKING_FEARTRACK),
    [TDL_MODEL_CLS_KEYPOINT_HAND_GESTURE]    = MODEL_NAME(TDL_MODEL_CLS_KEYPOINT_HAND_GESTURE),
    [TDL_MODEL_YOLOV8N_DET_HAND]             = MODEL_NAME(TDL_MODEL_YOLOV8N_DET_HAND),
    [TDL_MODEL_KEYPOINT_HAND]                = MODEL_NAME(TDL_MODEL_KEYPOINT_HAND),
    [TDL_MODEL_YOLOV8N_DET_LICENSE_PLATE]    = MODEL_NAME(TDL_MODEL_YOLOV8N_DET_LICENSE_PLATE),
    [TDL_MODEL_KEYPOINT_LICENSE_PLATE]       = MODEL_NAME(TDL_MODEL_KEYPOINT_LICENSE_PLATE),
    [TDL_MODEL_RECOGNITION_LICENSE_PLATE]    = MODEL_NAME(TDL_MODEL_RECOGNITION_LICENSE_PLATE),
    [TDL_MODEL_MBV2_DET_PERSON]              = MODEL_NAME(TDL_MODEL_MBV2_DET_PERSON),
    [TDL_MODEL_KEYPOINT_SIMCC_PERSON17]      = MODEL_NAME(TDL_MODEL_KEYPOINT_SIMCC_PERSON17),
    [TDL_MODEL_FEATURE_CLIP_IMG]             = MODEL_NAME(TDL_MODEL_FEATURE_CLIP_IMG),
    [TDL_MODEL_FEATURE_CLIP_TEXT]            = MODEL_NAME(TDL_MODEL_FEATURE_CLIP_TEXT)
};

const char ** app_ipcam_Param_get_ai_supported_model()
{
    return ai_supported_model;
}
