include $(SRCTREE)/build/rule.mk
TARGET_DIR := $(TARGET_OUT_DIR)/lib
TARGET_A := $(TARGET_DIR)/libapp_mbuf.a

SEXT	:= c
SDIR	+= $(CURDIR)/src
ODIR 	+= $(CURDIR)/obj

include $(SRCTREE)/build/build.mk
