include $(SRCTREE)/build/rule.mk
TARGET_DIR := $(TARGET_OUT_DIR)/lib
TARGET_A := $(TARGET_DIR)/libapp_media_blacklight.a

SEXT	:= c
SDIR	+= $(CURDIR)/src
ODIR 	+= $(CURDIR)/obj
#DEPEND
INCS									+= -I$(CURDIR)/include

include $(SRCTREE)/build/build.mk