// #ifndef __APP_IPCAM_AI_WRAPPER_H__
// #define __APP_IPCAM_AI_WRAPPER_H__

// /* struct-Core */
// typedef cviai_handle_t                                              cvitdl_handle_t;
// typedef cvai_object_t                                               cvtdl_object_t;
// typedef cvai_object_info_t                                          cvtdl_object_info_t;
// typedef cvai_face_t                                                 cvtdl_face_t;
// typedef cvai_feature_t                                              cvtdl_feature_t;
// typedef cvai_face_info_t                                            cvtdl_face_info_t;
// typedef cvai_pts_t                                                  cvtdl_pts_t;
// typedef cvai_bbox_t                                                 cvtdl_bbox_t;
// typedef cvai_vpssconfig_t                                           cvtdl_vpssconfig_t;
// typedef cvai_handpose21_meta_ts                                     cvtdl_handpose21_meta_ts;
// typedef cvai_handpose21_meta_t                                      cvtdl_handpose21_meta_t;
// /* struct-Service */
// typedef cviai_service_handle_t                                      cvitdl_service_handle_t;
// typedef cvai_service_brush_t                                        cvtdl_service_brush_t;
// typedef cvai_service_feature_array_t                                cvtdl_service_feature_array_t;
// /* struct-App */
// typedef cviai_app_handle_t                                          cvitdl_app_handle_t;

// /* macro */
// #define CVI_TDL_SUPPORTED_MODEL_RETINAFACE                          CVI_AI_SUPPORTED_MODEL_RETINAFACE
// #define CVI_TDL_SUPPORTED_MODEL_SCRFDFACE                           CVI_AI_SUPPORTED_MODEL_SCRFDFACE
// #define CVI_TDL_SUPPORTED_MODEL_RETINAFACE_IR                       CVI_AI_SUPPORTED_MODEL_RETINAFACE_IR
// #define CVI_TDL_SUPPORTED_MODEL_RETINAFACE_HARDHAT                  CVI_AI_SUPPORTED_MODEL_RETINAFACE_HARDHAT
// #define CVI_TDL_SUPPORTED_MODEL_THERMALFACE                         CVI_AI_SUPPORTED_MODEL_THERMALFACE
// #define CVI_TDL_SUPPORTED_MODEL_THERMALPERSON                       CVI_AI_SUPPORTED_MODEL_THERMALPERSON
// #define CVI_TDL_SUPPORTED_MODEL_FACEATTRIBUTE                       CVI_AI_SUPPORTED_MODEL_FACEATTRIBUTE
// #define CVI_TDL_SUPPORTED_MODEL_FACERECOGNITION                     CVI_AI_SUPPORTED_MODEL_FACERECOGNITION
// #define CVI_TDL_SUPPORTED_MODEL_MASKFACERECOGNITION                 CVI_AI_SUPPORTED_MODEL_MASKFACERECOGNITION
// #define CVI_TDL_SUPPORTED_MODEL_FACEQUALITY                         CVI_AI_SUPPORTED_MODEL_FACEQUALITY
// #define CVI_TDL_SUPPORTED_MODEL_MASKCLASSIFICATION                  CVI_AI_SUPPORTED_MODEL_MASKCLASSIFICATION
// #define CVI_TDL_SUPPORTED_MODEL_HANDCLASSIFICATION                  CVI_AI_SUPPORTED_MODEL_HANDCLASSIFICATION
// #define CVI_TDL_SUPPORTED_MODEL_HAND_KEYPOINT                       CVI_AI_SUPPORTED_MODEL_HAND_KEYPOINT
// #define CVI_TDL_SUPPORTED_MODEL_HAND_KEYPOINT_CLASSIFICATION        CVI_AI_SUPPORTED_MODEL_HAND_KEYPOINT_CLASSIFICATION
// #define CVI_TDL_SUPPORTED_MODEL_LIVENESS                            CVI_AI_SUPPORTED_MODEL_LIVENESS
// #define CVI_TDL_SUPPORTED_MODEL_HAND_DETECTION                      CVI_AI_SUPPORTED_MODEL_HAND_DETECTION
// #define CVI_TDL_SUPPORTED_MODEL_MOBILEDETV2_PERSON_VEHICLE          CVI_AI_SUPPORTED_MODEL_MOBILEDETV2_PERSON_VEHICLE
// #define CVI_TDL_SUPPORTED_MODEL_MOBILEDETV2_VEHICLE                 CVI_AI_SUPPORTED_MODEL_MOBILEDETV2_VEHICLE
// #define CVI_TDL_SUPPORTED_MODEL_MOBILEDETV2_PEDESTRIAN              CVI_AI_SUPPORTED_MODEL_MOBILEDETV2_PEDESTRIAN
// #define CVI_TDL_SUPPORTED_MODEL_MOBILEDETV2_PERSON_PETS             CVI_AI_SUPPORTED_MODEL_MOBILEDETV2_PERSON_PETS
// #define CVI_TDL_SUPPORTED_MODEL_MOBILEDETV2_COCO80                  CVI_AI_SUPPORTED_MODEL_MOBILEDETV2_COCO80
// #define CVI_TDL_SUPPORTED_MODEL_YOLOV3                              CVI_AI_SUPPORTED_MODEL_YOLOV3
// #define CVI_TDL_SUPPORTED_MODEL_YOLOV5                              CVI_AI_SUPPORTED_MODEL_YOLOV5
// #define CVI_TDL_SUPPORTED_MODEL_YOLOV6                              CVI_AI_SUPPORTED_MODEL_YOLOV6
// #define CVI_TDL_SUPPORTED_MODEL_YOLOV7                              CVI_AI_SUPPORTED_MODEL_YOLOV7
// #define CVI_TDL_SUPPORTED_MODEL_YOLO                                CVI_AI_SUPPORTED_MODEL_YOLO
// #define CVI_TDL_SUPPORTED_MODEL_YOLOX                               CVI_AI_SUPPORTED_MODEL_YOLOX
// #define CVI_TDL_SUPPORTED_MODEL_PPYOLOE                             CVI_AI_SUPPORTED_MODEL_PPYOLOE
// #define CVI_TDL_SUPPORTED_MODEL_OSNET                               CVI_AI_SUPPORTED_MODEL_OSNET
// #define CVI_TDL_SUPPORTED_MODEL_SOUNDCLASSIFICATION                 CVI_AI_SUPPORTED_MODEL_SOUNDCLASSIFICATION
// #define CVI_TDL_SUPPORTED_MODEL_SOUNDCLASSIFICATION_V2              CVI_AI_SUPPORTED_MODEL_SOUNDCLASSIFICATION_V2
// #define CVI_TDL_SUPPORTED_MODEL_WPODNET                             CVI_AI_SUPPORTED_MODEL_WPODNET
// #define CVI_TDL_SUPPORTED_MODEL_LPRNET_TW                           CVI_AI_SUPPORTED_MODEL_LPRNET_TW
// #define CVI_TDL_SUPPORTED_MODEL_LPRNET_CN                           CVI_AI_SUPPORTED_MODEL_LPRNET_CN
// #define CVI_TDL_SUPPORTED_MODEL_DEEPLABV3                           CVI_AI_SUPPORTED_MODEL_DEEPLABV3
// #define CVI_TDL_SUPPORTED_MODEL_ALPHAPOSE                           CVI_AI_SUPPORTED_MODEL_ALPHAPOSE
// #define CVI_TDL_SUPPORTED_MODEL_EYECLASSIFICATION                   CVI_AI_SUPPORTED_MODEL_EYECLASSIFICATION
// #define CVI_TDL_SUPPORTED_MODEL_YAWNCLASSIFICATION                  CVI_AI_SUPPORTED_MODEL_YAWNCLASSIFICATION
// #define CVI_TDL_SUPPORTED_MODEL_FACELANDMARKER                      CVI_AI_SUPPORTED_MODEL_FACELANDMARKER
// #define CVI_TDL_SUPPORTED_MODEL_FACELANDMARKERDET2                  CVI_AI_SUPPORTED_MODEL_FACELANDMARKERDET2
// #define CVI_TDL_SUPPORTED_MODEL_INCAROBJECTDETECTION                CVI_AI_SUPPORTED_MODEL_INCAROBJECTDETECTION
// #define CVI_TDL_SUPPORTED_MODEL_SMOKECLASSIFICATION                 CVI_AI_SUPPORTED_MODEL_SMOKECLASSIFICATION
// #define CVI_TDL_SUPPORTED_MODEL_FACEMASKDETECTION                   CVI_AI_SUPPORTED_MODEL_FACEMASKDETECTION
// #define CVI_TDL_SUPPORTED_MODEL_IRLIVENESS                          CVI_AI_SUPPORTED_MODEL_IRLIVENESS
// #define CVI_TDL_SUPPORTED_MODEL_PERSON_PETS_DETECTION               CVI_AI_SUPPORTED_MODEL_PERSON_PETS_DETECTION
// #define CVI_TDL_SUPPORTED_MODEL_YOLOV8_DETECTION                    CVI_AI_SUPPORTED_MODEL_YOLOV8_DETECTION
// #define CVI_TDL_SUPPORTED_MODEL_PERSON_VEHICLE_DETECTION            CVI_AI_SUPPORTED_MODEL_PERSON_VEHICLE_DETECTION
// #define CVI_TDL_SUPPORTED_MODEL_HAND_FACE_PERSON_DETECTION          CVI_AI_SUPPORTED_MODEL_HAND_FACE_PERSON_DETECTION
// #define CVI_TDL_SUPPORTED_MODEL_HEAD_PERSON_DETECTION               CVI_AI_SUPPORTED_MODEL_HEAD_PERSON_DETECTION
// #define CVI_TDL_SUPPORTED_MODEL_YOLOV8POSE                          CVI_AI_SUPPORTED_MODEL_YOLOV8POSE
// #define CVI_TDL_SUPPORTED_MODEL_SIMCC_POSE                          CVI_AI_SUPPORTED_MODEL_SIMCC_POSE
// #define CVI_TDL_SUPPORTED_MODEL_LANDMARK_DET3                       CVI_AI_SUPPORTED_MODEL_LANDMARK_DET3
// #define CVI_TDL_SUPPORTED_MODEL_LP_RECONGNITION                     CVI_AI_SUPPORTED_MODEL_LP_RECONGNITION
// #define CVI_TDL_SUPPORTED_MODEL_LP_DETECTION                        CVI_AI_SUPPORTED_MODEL_LP_DETECTION
// #define CVI_TDL_SUPPORTED_MODEL_IMAGE_CLASSIFICATION                CVI_AI_SUPPORTED_MODEL_IMAGE_CLASSIFICATION
// #define CVI_TDL_SUPPORTED_MODEL_HRNET_POSE                          CVI_AI_SUPPORTED_MODEL_HRNET_POSE
// #define CVI_TDL_SUPPORTED_MODEL_DMSLANDMARKERDET                    CVI_AI_SUPPORTED_MODEL_DMSLANDMARKERDET
// #define CVI_TDL_SUPPORTED_MODEL_END                                 CVI_AI_SUPPORTED_MODEL_END

// #define CVI_TDL_DET_TYPE_PERSON                                     CVI_AI_DET_TYPE_PERSON
// #define CVI_TDL_DET_TYPE_BICYCLE                                    CVI_AI_DET_TYPE_BICYCLE
// #define CVI_TDL_DET_TYPE_CAR                                        CVI_AI_DET_TYPE_CAR
// #define CVI_TDL_DET_TYPE_MOTORBIKE                                  CVI_AI_DET_TYPE_MOTORBIKE
// #define CVI_TDL_DET_TYPE_TRUCK                                      CVI_AI_DET_TYPE_TRUCK
// #define CVI_TDL_DET_TYPE_BUS                                        CVI_AI_DET_TYPE_BUS

// #define CVI_TDL_SUCCESS                                             CVIAI_SUCCESS
// #define CVI_TDL_FAILURE                                             CVIAI_FAILURE

// /* function-Core */
// #define CVI_TDL_CreateHandle                                        CVI_AI_CreateHandle
// #define CVI_TDL_DestroyHandle                                       CVI_AI_DestroyHandle
// #define CVI_TDL_Service_CreateHandle                                CVI_AI_Service_CreateHandle
// #define CVI_TDL_Service_DestroyHandle                               CVI_AI_Service_DestroyHandle
// #define CVI_TDL_SUPPORTED_MODEL_E                                   CVI_AI_SUPPORTED_MODEL_E
// #define CVI_TDL_OpenModel                                           CVI_AI_OpenModel
// #define CVI_TDL_SetModelThreshold                                   CVI_AI_SetModelThreshold
// #define CVI_TDL_ScrFDFace                                           CVI_AI_ScrFDFace
// #define CVI_TDL_FaceRecognition                                     CVI_AI_FaceRecognition
// #define CVI_TDL_Service_RegisterFeatureArray                        CVI_AI_Service_RegisterFeatureArray
// #define CVI_TDL_Free                                                CVI_AI_Free
// #define CVI_TDL_FaceRecognitionOne                                  CVI_AI_FaceRecognitionOne
// #define CVI_TDL_Service_CalculateSimilarity                         CVI_AI_Service_CalculateSimilarity
// #define CVI_TDL_SetSkipVpssPreprocess                               CVI_AI_SetSkipVpssPreprocess
// #define CVI_TDL_SetVBPool                                           CVI_AI_SetVBPool
// #define CVI_TDL_CopyInfo                                            CVI_AI_CopyInfo
// #define CVI_TDL_CopyObjectInfo                                      CVI_AI_CopyObjectInfo
// #define CVI_TDL_RetinaFace_Hardhat                                  CVI_AI_RetinaFace_Hardhat
// #define CVI_TDL_SetVpssTimeout                                      CVI_AI_SetVpssTimeout
// #define CVI_TDL_GetVpssChnConfig                                    CVI_AI_GetVpssChnConfig
// #define CVI_TDL_RescaleMetaRB                                       CVI_AI_RescaleMetaRB
// #define CVI_TDL_MobileDetV2_Pedestrian                              CVI_AI_MobileDetV2_Pedestrian
// #define CVI_TDL_MobileDetV2_Vehicle                                 CVI_AI_MobileDetV2_Vehicle
// #define CVI_TDL_MobileDetV2_Person_Vehicle                          CVI_AI_MobileDetV2_Person_Vehicle
// #define CVI_TDL_PersonPet_Detection                                 CVI_AI_PersonPet_Detection
// #define CVI_TDL_Hand_Detection                                      CVI_AI_Hand_Detection
// #define CVI_TDL_HandKeypoint                                        CVI_AI_HandKeypoint
// #define CVI_TDL_HandKeypointClassification                          CVI_AI_HandKeypointClassification
// #define CVI_TDL_SoundClassification_V2                              CVI_AI_SoundClassification_V2
// #define CVI_TDL_SetPerfEvalInterval                                 CVI_AI_SetPerfEvalInterval
// #define CVI_TDL_SelectDetectClass                                   CVI_AI_SelectDetectClass
// #define CVI_TDL_IrLiveness                                          CVI_AI_IrLiveness

// /* function-Service */
// #define CVI_TDL_Service_FaceDrawRect                                CVI_AI_Service_FaceDrawRect
// #define CVI_TDL_Service_ObjectDrawRect                              CVI_AI_Service_ObjectDrawRect
// #define CVI_TDL_Service_Polygon_Intersect                           CVI_AI_Service_Polygon_Intersect
// #define CVI_TDL_Service_Polygon_SetTarget                           CVI_AI_Service_Polygon_SetTarget

// /* function-App */
// #define CVI_TDL_APP_CreateHandle                                    CVI_AI_APP_CreateHandle
// #define CVI_TDL_APP_DestroyHandle                                   CVI_AI_APP_DestroyHandle
// #define CVI_TDL_APP_FaceCapture_Init                                CVI_AI_APP_FaceCapture_Init
// #define CVI_TDL_APP_FaceCapture_SetConfig                           CVI_AI_APP_FaceCapture_SetConfig
// #define CVI_TDL_APP_FaceCapture_Run                                 CVI_AI_APP_FaceCapture_Run
// #define CVI_TDL_APP_FaceCapture_QuickSetUp                          CVI_AI_APP_FaceCapture_QuickSetUp
// #define CVI_TDL_APP_FaceCapture_SetMode                             CVI_AI_APP_FaceCapture_SetMode
// #define CVI_TDL_APP_PersonCapture_Init                              CVI_AI_APP_PersonCapture_Init
// #define CVI_TDL_APP_PersonCapture_QuickSetUp                        CVI_AI_APP_PersonCapture_QuickSetUp
// #define CVI_TDL_APP_ConsumerCounting_Line                           CVI_AI_APP_ConsumerCounting_Line
// #define CVI_TDL_APP_PersonCapture_GetDefaultConfig                  CVI_AI_APP_PersonCapture_GetDefaultConfig
// #define CVI_TDL_APP_PersonCapture_SetConfig                         CVI_AI_APP_PersonCapture_SetConfig
// #define CVI_TDL_APP_ConsumerCounting_Run                            CVI_AI_APP_ConsumerCounting_Run

// #endif